version: 0.0
os: linux

files:
  - source: /
    destination: /opt/github-actions-practice
permissions:
  - object: /opt/github-actions-practice/
    owner: ec2-user
    group: ec2-user
    mode: 755
hooks:
  AfterInstall:
    # location은 프로젝트의 root경로를 기준
    - location: deploy.sh
      timeout: 60
      runas: ec2-user