name: Deploy Spring boot to AWS EC2

on:
  push:
    branches:
      - master

env:
  PROJECT_NAME: github-actions-practice
  BUCKET: github-actions-exercise-build

jobs:
  deploy:
    name: DEPLOY
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew build
        shell: bash

      - name: MAKE DEPLOYMENT DIR
        run: mkdir -p code-deploy-${PROJECT_NAME}

      - name: MOVE DEPLOY CODE DEPLOY SCRIPT
        run: cp ${PROJECT_NAME}/code-deploy/* code-deploy-${PROJECT_NAME}/

      - name: MOVE BUILD JAR
        run: cp ${PROJECT_NAME}/build/libs/*.jar code-deploy-${PROJECT_NAME}/
      
      - name: Make zip file
        run: zip -r -j code-deploy-${PROJECT_NAME} code-deploy-${PROJECT_NAME}/*
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: aws s3 cp code-deploy-${PROJECT_NAME}.zip s3://${BUCKET}/${PROJECT_NAME}/${PROJECT_NAME}-${GITHUB_SHA}.zip --region ap-northeast-2

      - name: Code Deploy
        run: aws deploy create-deployment --application-name ${PROJECT_NAME}-deploy --deployment-group-name ${PROJECT_NAME}-deploy-group --region ap-northeast-2 --s3-location bucket=${BUCKET},bundleType=zip,key=${PROJECT_NAME}/${PROJECT_NAME}-${GITHUB_SHA}.zip
